version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid-railgun-fiber-sepolia-v2
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT:-23798}:5432"
    shm_size: 1gb
    volumes:
      - squid-db:/var/lib/postgresql/data

volumes:
  squid-db:
